### ISSUE TITLE
delegation and verify_mic

### ISSUE THREAD

**Issue by akostadinov** [zenchild/gssapi#22]
Hello, I see one commit not merged to this project:
https://github.com/MerckAppDevelopment/gssapi/commit/1734f75bcc245b91128d8a20630b70c7bec4f964

Was there any reason to not merge or author simply did not submit?

**Comment by pavel-jurasek-merck-com** [comment]
@akostadinov i merge this commit to our fork just becouse we planned to use this functionality already nothing more.
