### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by vLukas-dev** [zenchild/gssapi#30]
Since [the original issue](https://github.com/zenchild/gssapi/issues/12) was closed even though the root cause is yet unsolved, I'm opening this for visibility.

**Comment by lucywyman** [comment]
We use this lib as a dependency, and users are seeing the same issue (trying to connect over SSH authenticating with Kerberos from RedHat 7).
Versions:
gssapi gem: 1.3.0
net-ssh-krb: 0.5.1

**Comment by zenchild** [comment]
I'm going to reopen the other issue and close this one. stay tuned there :)
